"""Tabelas de lookup do Bsoft TMS (dados puros, extraidas de gerenciador_atlantico/shared.py)."""
from __future__ import annotations

BSOFT_CATEGORY_ID_TO_RODADO_ID_MAP = {
    7: "00",
    8: "05",
    11: "01",
    3: "00",
    1: "03",
    9: "03",
    10: "03",
    2: "00",
    12: "00",
    13: "00",
    4: "01",
    6: "02",
    5: "04",
}

BSOFT_MARCA_ID_LOOKUP = {
    ("SCANIA", "CAVALO"): 1, ("VOLVO", "CAVALO"): 2, ("IVECO", "CAVALO"): 3, ("VOLKSWAGEN", "CAVALO"): 4,
    ("GUERRA", "CARRETA"): 5, ("GUERRA", "SEMI-REBOQUE 1"): 7, ("FORD", "CAVALO"): 8, ("MERCEDES BENZ", "CAVALO"): 9,
    ("SCHIFFER", "SEMI-REBOQUE 1"): 11, ("RANDON", "SEMI-REBOQUE 1"): 12, ("FACCHINI", "SEMI-REBOQUE 1"): 13,
    ("NOMA", "SEMI-REBOQUE 1"): 14, ("REB KRONE", "SEMI-REBOQUE 1"): 15, ("FIAT", "CAVALO"): 17,
    ("FACCHINI", "CARRETA"): 18, ("NOMA", "CARRETA"): 19, ("RANDON", "CARRETA"): 20, ("LIBRELATO", "CARRETA"): 21,
    ("SCHIFFER", "CARRETA"): 22, ("SERRATO", "CARRETA"): 24, ("KRONE", "CARRETA"): 26, ("NAVISTAR", "CAVALO"): 27,
    ("MARCOFRIO", "CARRETA"): 28, ("CHARGER", "CARRETA"): 29, ("ANTONINI", "CARRETA"): 30,
    ("ANTONINI", "SEMI-REBOQUE 1"): 31, ("RODOLINEA", "CARRETA"): 32, ("RODOLINEA", "SEMI-REBOQUE 1"): 33,
    ("ROSSETTI", "CARRETA"): 34, ("LIBRELATO", "SEMI-REBOQUE 1"): 35, ("RECRUSUL", "CARRETA"): 36,
    ("FNV", "CARRETA"): 37, ("IDEROL", "CARRETA"): 38, ("SAN MARINO", "CARRETA"): 39,
    ("PASTRE", "SEMI-REBOQUE 1"): 40, ("PIKO", "CARRETA"): 41, ("GOTTI", "CARRETA"): 42, ("VOLVO", "TRUCK"): 43,
    ("MERCEDES BENZ", "TRUCK"): 44, ("VW", "TRUCK"): 45, ("FORD", "TRUCK"): 46, ("SCANIA", "TRUCK"): 47,
    ("FIAT", "TRUCK"): 48, ("HYUNDAI", "TOCO"): 49, ("KIA", "TOCO"): 50, ("FIAT", "AUTOMÓVEIS"): 51,
    ("SCANIA", "CAVALO 4 EIXOS"): 52, ("SCANIA", "CAVALO TRUCADO 3 EIXOS"): 53, ("SCANIA", "BITRUCK"): 54,
    ("MAN", "CAVALO"): 55, ("SR", "SEMI-REBOQUE 1"): 56, ("GUERRA", "SEMI-REBOQUE 2"): 57, ("IVECO", "TRUCK"): 58,
    ("IRMAOS CLARA", "SEMI-REBOQUE 1"): 59, ("ROSSETTI", "SEMI-REBOQUE 1"): 60,
    ("IDEROL", "SEMI-REBOQUE 1"): 61, ("SAO PEDRO", "SEMI-REBOQUE 1"): 62, ("ALFASTEEL", "SEMI-REBOQUE 1"): 63,
    ("VOLVO", "CAVALO TRUCADO 3 EIXOS"): 64, ("RANDONSP", "SEMI-REBOQUE 1"): 65,
    ("LIBRELATO", "SEMI-REBOQUE 2"): 66, ("TRIELHT", "SEMI-REBOQUE 1"): 67, ("DAF", "TRUCK"): 68,
    ("TECTRAN", "SEMI-REBOQUE 1"): 69, ("DAF", "CAVALO"): 70, ("ESTRADA", "SEMI-REBOQUE 1"): 71,
    ("VW", "CAVALO"): 72, ("NEW-G", "SEMI-REBOQUE 1"): 73, ("NEW-G", "SEMI-REBOQUE 2"): 74,
    ("NOMA", "SEMI-REBOQUE 2"): 75, ("RANDON", "SEMI-REBOQUE 2"): 76, ("FACCHINI", "SEMI-REBOQUE 2"): 77,
    ("RODOFORTSA", "SEMI-REBOQUE 1"): 78, ("UNICARR", "SEMI-REBOQUE 1"): 79,
}

BSOFT_CATEGORIAS_VEICULO = {
    "CAVALO": 1, "SEMI-REBOQUE 1": 2, "CARRETA": 3, "TRUCK": 4, "VAN": 5, "TOCO": 6,
    "3/4": 7, "AUTOMÓVEIS": 8, "CAVALO 4 EIXOS": 9, "CAVALO TRUCADO 3 EIXOS": 10,
    "BITRUCK": 11, "SEMI-REBOQUE 2": 12, "DOLLY": 13,
}

BSOFT_TIPOS_EQUIPAMENTO = {
    "TOCO": 1, "3/4": 2, "CARRETA SIMPLES": 3, "CAVALO": 4, "TRUCK": 5, "AUTOMÓVEIS": 7, "CAVALO 4 EIXOS": 8,
    "CAVALO TRUCADO 3 EIXOS": 9, "BITRUCK": 10, "CARRETA 3 EIXOS": 11, "CARRETA VANDERLEIA 3 EIXOS ESPAÇADOS": 12,
    "CARRETA 4º EIXOS": 13, "SEMI-REBOQUE 1": 14, "SEMI-REBOQUE 2": 15, "DOLLY": 16,
}

BSOFT_GRUPOS_VEICULO = {
    "FROTA PROPRIA": 1,
    "FROTA DE TERCEIROS": 2,
}

BSOFT_CATEGORY_TO_EQUIPMENT_MAP = {
    1: 4, 2: 14, 3: 11, 4: 5, 6: 1, 7: 2, 8: 7, 9: 8, 10: 9, 11: 10, 12: 15, 13: 16,
}

BSOFT_TIPOS_RODADO_NOMES = {
    "00": "NÃO APLICÁVEL", "01": "TRUCK", "02": "TOCO", "03": "CAVALO MECANICO",
    "04": "VAN", "05": "UTILITARIO", "06": "OUTROS",
}

BSOFT_TIPOS_CARROCERIA_NOMES = {
    "00": "NÃO APLICAVEL", "01": "ABERTA", "02": "FECHADA/BAÚ", "03": "GRANELEIRA",
    "04": "PORTA CONTAINER", "05": "SIDER",
}

BSOFT_CATEGORY_TO_SIMPLE_BRANDS_MAP = {
    "CAVALO": ["SCANIA", "VOLVO", "IVECO", "VOLKSWAGEN", "FORD", "MERCEDES BENZ", "FIAT", "NAVISTAR", "MAN", "DAF", "VW"],
    "SEMI-REBOQUE 1": ["GUERRA", "SCHIFFER", "RANDON", "FACCHINI", "NOMA", "REB KRONE", "ANTONINI", "RODOLINEA", "LIBRELATO", "PASTRE", "SR", "IRMAOS CLARA", "ROSSETTI", "IDEROL", "SAO PEDRO", "ALFASTEEL", "RANDONSP", "TRIELHT", "TECTRAN", "ESTRADA", "NEW-G", "RODOFORTSA", "UNICARR"],
    "CARRETA": ["GUERRA", "FACCHINI", "NOMA", "RANDON", "LIBRELATO", "SCHIFFER", "SERRATO", "KRONE", "MARCOFRIO", "CHARGER", "ANTONINI", "RODOLINEA", "ROSSETTI", "RECRUSUL", "FNV", "IDEROL", "SAN MARINO", "PIKO", "GOTTI"],
    "TRUCK": ["VOLVO", "MERCEDES BENZ", "VW", "FORD", "SCANIA", "FIAT", "IVECO", "DAF"],
    "TOCO": ["HYUNDAI", "KIA"],
    "AUTOMÓVEIS": ["FIAT"],
    "CAVALO 4 EIXOS": ["SCANIA"],
    "CAVALO TRUCADO 3 EIXOS": ["SCANIA", "VOLVO"],
    "BITRUCK": ["SCANIA"],
    "SEMI-REBOQUE 2": ["GUERRA", "LIBRELATO", "NEW-G", "NOMA", "RANDON", "FACCHINI"],
}

BSOFT_SIMPLE_BRANDS_LIST = sorted(
    {marca for marca, _categoria in BSOFT_MARCA_ID_LOOKUP.keys()}, key=len, reverse=True
)
